general template for now
LucasDrager/CSCI-3308-Group-5-Final-Project pull request #2
Opened 2023-11-08 00:05 UTC by nasirnaqvi

2023-11-08 00:18 UTC, nasirnaqvi commented
ERD Diagram in DBML:  [https://dbdiagram.io/d/654ad3937d8bbd6465b5ffa1](https://dbdiagram.io/d/654ad3937d8bbd6465b5ffa1)

2023-11-09 22:18 UTC, LucasDrager requested changes
Add password to user table.

2023-11-09 22:19 UTC, LucasDrager reviewed
Looks all good now!

2023-11-09 22:20 UTC, LucasDrager approved these changes

2023-11-09 22:20 UTC, merged